version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nodejs-pg-backend-container
    environment:
      - APP_PORT=3005
    ports:
      - "3005:3005"
    restart: unless-stopped
    working_dir: /app
    env_file:
      - .env
    volumes:
      - /var/www/backend-V1-D/uploads:/app/uploads
      - /var/www/backend-V1-D/logs:/app/logs
    networks:
      - backend-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3005"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - node_modules/
            - uploads/
            - .git/
        - action: rebuild
          path: package*.json

networks:
  backend-network:
    driver: bridge
